/* eslint-disable i18next/no-literal-string -- CloudGuard Workspace Operations → Automation */
import React from "react";
import {
  Cog,
  FileCode2,
  CalendarClock,
  Rocket,
  Layers,
  History,
  Plug,
  Plus,
  Play,
  Pause,
  RefreshCcw,
  Download,
} from "lucide-react";
import {
  OpsLeaf,
  WORKSPACES,
  OWNERS,
  type Leaf,
  type OpsLeafConfig,
} from "#/components/admin/pages/workspace-operations/ops-leaf";

/**
 * Automation — the machinery that operates the estate without a human in the loop:
 * the automation policies that decide when to act, the templates they apply, the
 * scheduled tasks and provisioning jobs that run, the bulk operations across many
 * workspaces, the execution history, and the notification integrations they emit
 * through. Authoritative spec:
 * docs/workspace/workspace_module/…/Workspace Operations/Automation/.
 */

const TRIGGERS = ["Schedule", "Event", "Threshold", "Manual", "Webhook"];
const RUN_STATUS = ["Succeeded", "Succeeded", "Succeeded", "Running", "Failed"];

const POLICIES: OpsLeafConfig = {
  entity: "automation policy",
  title: "Automation policies",
  desc: "The rules that decide when automation acts — trigger, condition and the action it takes across matching workspaces.",
  icon: Cog,
  idPrefix: "AP",
  count: 16,
  initialSortKey: "runs",
  fields: [
    {
      key: "name",
      header: "Policy",
      kind: "primary",
      pool: [
        "Auto-tag new resources",
        "Idle sandbox cleanup",
        "Nightly compliance scan",
        "Quota auto-raise",
        "Drift auto-remediate",
        "Cost anomaly response",
        "Expiry reminder",
        "Snapshot rotation",
      ],
      searchable: true,
    },
    {
      key: "trigger",
      header: "Trigger",
      kind: "text",
      pool: TRIGGERS,
      filter: true,
    },
    {
      key: "action",
      header: "Action",
      kind: "text",
      pool: ["Tag", "Notify", "Remediate", "Scale", "Snapshot", "Decommission"],
      filter: true,
    },
    { key: "owner", header: "Owner", kind: "text", pool: OWNERS, filter: true },
    { key: "runs", header: "Runs (30d)", kind: "num", min: 0, max: 900 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Paused", "Draft"],
      filter: true,
    },
  ],
  stats: [
    { label: "Policies", kind: "count" },
    {
      label: "Active",
      kind: "where",
      field: "status",
      eq: ["Active"],
      tone: "ok",
    },
    {
      label: "Paused",
      kind: "where",
      field: "status",
      eq: ["Paused"],
      tone: "warn",
    },
    { label: "Runs (30d)", kind: "sum", field: "runs" },
  ],
  toolbar: [
    { label: "New Policy", icon: <Plus size={15} />, primary: true },
    { label: "Enable", icon: <Play size={15} /> },
    { label: "Pause", icon: <Pause size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Run Now", "Pause", "Disable"],
  bulk: [
    { label: "Enable", icon: <Play size={13} /> },
    { label: "Pause", icon: <Pause size={13} /> },
  ],
};

const TEMPLATES: OpsLeafConfig = {
  entity: "template",
  title: "Automation templates",
  desc: "Reusable, versioned blueprints automation applies — workspace scaffolds, resource bundles and remediation playbooks.",
  icon: FileCode2,
  idPrefix: "TPL",
  count: 15,
  initialSortKey: "uses",
  fields: [
    {
      key: "name",
      header: "Template",
      kind: "primary",
      pool: [
        "Standard Workspace",
        "PCI Workspace",
        "Data Science Kit",
        "Landing Zone",
        "Break-Glass Access",
        "Cost-Optimized",
        "DR Pair",
        "Sandbox",
      ],
      searchable: true,
    },
    {
      key: "category",
      header: "Category",
      kind: "text",
      pool: ["Workspace", "Resource", "Remediation", "Access"],
      filter: true,
    },
    { key: "version", header: "Version", kind: "mono", pool: ["v"] },
    { key: "owner", header: "Owner", kind: "text", pool: OWNERS, filter: true },
    { key: "uses", header: "Uses", kind: "num", min: 0, max: 400 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Published", "Published", "Draft", "Deprecated"],
      filter: true,
    },
  ],
  stats: [
    { label: "Templates", kind: "count" },
    {
      label: "Published",
      kind: "where",
      field: "status",
      eq: ["Published"],
      tone: "ok",
    },
    {
      label: "Deprecated",
      kind: "where",
      field: "status",
      eq: ["Deprecated"],
      tone: "warn",
    },
    { label: "Total Uses", kind: "sum", field: "uses" },
  ],
  toolbar: [
    { label: "New Template", icon: <Plus size={15} />, primary: true },
    { label: "Publish", icon: <Rocket size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Publish", "Duplicate", "Deprecate"],
};

const SCHEDULED: OpsLeafConfig = {
  entity: "scheduled task",
  title: "Scheduled tasks",
  desc: "Time-based automation — the recurring tasks that run on a schedule, their cadence, next run and last result.",
  icon: CalendarClock,
  idPrefix: "SCH",
  count: 16,
  initialSortKey: "nextRun",
  fields: [
    {
      key: "name",
      header: "Task",
      kind: "primary",
      pool: [
        "Nightly scan",
        "Weekly cost report",
        "Snapshot rotation",
        "Idle cleanup",
        "Cert renewal",
        "Access review",
        "Backup verify",
        "Drift check",
      ],
      searchable: true,
    },
    {
      key: "cadence",
      header: "Cadence",
      kind: "text",
      pool: ["Hourly", "Daily", "Weekly", "Monthly"],
      filter: true,
    },
    {
      key: "workspace",
      header: "Scope",
      kind: "text",
      pool: ["Organization", ...WORKSPACES],
      filter: true,
      searchable: true,
    },
    {
      key: "nextRun",
      header: "Next Run",
      kind: "rel",
      pool: ["in 20 min", "in 3 h", "tomorrow", "in 2 days"],
    },
    {
      key: "lastResult",
      header: "Last Result",
      kind: "status",
      pool: ["Succeeded", "Succeeded", "Failed"],
      filter: true,
    },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Paused"],
      filter: true,
    },
  ],
  stats: [
    { label: "Scheduled Tasks", kind: "count" },
    {
      label: "Active",
      kind: "where",
      field: "status",
      eq: ["Active"],
      tone: "ok",
    },
    {
      label: "Failed Last Run",
      kind: "where",
      field: "lastResult",
      eq: ["Failed"],
      tone: "danger",
    },
    {
      label: "Paused",
      kind: "where",
      field: "status",
      eq: ["Paused"],
      tone: "warn",
    },
  ],
  toolbar: [
    { label: "New Task", icon: <Plus size={15} />, primary: true },
    { label: "Run Now", icon: <Play size={15} /> },
    { label: "Pause", icon: <Pause size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Run Now", "Pause", "Delete"],
};

const JOBS: OpsLeafConfig = {
  entity: "provisioning job",
  title: "Provisioning jobs",
  desc: "The provisioning engine's worklist — every stand-up, change and tear-down job, its progress and outcome.",
  icon: Rocket,
  idPrefix: "JOB",
  count: 20,
  initialSortKey: "started",
  fields: [
    {
      key: "name",
      header: "Job",
      kind: "primary",
      pool: [
        "Provision workspace",
        "Add resources",
        "Apply template",
        "Scale cluster",
        "Tear down",
        "Rotate secrets",
        "Migrate data",
      ],
      searchable: true,
    },
    {
      key: "workspace",
      header: "Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
      searchable: true,
    },
    {
      key: "trigger",
      header: "Trigger",
      kind: "text",
      pool: TRIGGERS,
      filter: true,
    },
    { key: "progress", header: "Progress", kind: "pct", min: 0, max: 100 },
    {
      key: "duration",
      header: "Duration",
      kind: "rel",
      pool: ["45s", "2 min", "12 min", "26 min"],
    },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: RUN_STATUS,
      filter: true,
    },
    { key: "started", header: "Started", kind: "date" },
  ],
  stats: [
    { label: "Jobs", kind: "count" },
    {
      label: "Running",
      kind: "where",
      field: "status",
      eq: ["Running"],
      tone: "warn",
    },
    {
      label: "Failed",
      kind: "where",
      field: "status",
      eq: ["Failed"],
      tone: "danger",
    },
    {
      label: "Succeeded",
      kind: "where",
      field: "status",
      eq: ["Succeeded"],
      tone: "ok",
    },
  ],
  toolbar: [
    { label: "New Job", icon: <Plus size={15} />, primary: true },
    { label: "Retry", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Retry", "Cancel", "View Logs"],
};

const BULK: OpsLeafConfig = {
  entity: "bulk operation",
  title: "Bulk operations",
  desc: "Fan-out actions across many workspaces at once — the operation, its target set, per-target progress and rollback state.",
  icon: Layers,
  idPrefix: "BLK",
  count: 14,
  initialSortKey: "started",
  fields: [
    {
      key: "name",
      header: "Operation",
      kind: "primary",
      pool: [
        "Apply policy",
        "Retag",
        "Rotate keys",
        "Upgrade agent",
        "Enforce baseline",
        "Archive idle",
        "Reprice",
      ],
      searchable: true,
    },
    { key: "targets", header: "Targets", kind: "num", min: 2, max: 120 },
    {
      key: "trigger",
      header: "Trigger",
      kind: "text",
      pool: ["Manual", "Scheduled"],
      filter: true,
    },
    { key: "owner", header: "Owner", kind: "text", pool: OWNERS, filter: true },
    { key: "progress", header: "Progress", kind: "pct", min: 0, max: 100 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Running", "Completed", "Completed", "Failed"],
      filter: true,
    },
    { key: "started", header: "Started", kind: "date" },
  ],
  stats: [
    { label: "Operations", kind: "count" },
    {
      label: "Running",
      kind: "where",
      field: "status",
      eq: ["Running"],
      tone: "warn",
    },
    {
      label: "Failed",
      kind: "where",
      field: "status",
      eq: ["Failed"],
      tone: "danger",
    },
    { label: "Targets Affected", kind: "sum", field: "targets" },
  ],
  toolbar: [
    { label: "New Bulk Operation", icon: <Plus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "View Targets", "Retry Failed", "Roll Back"],
};

const EXECUTION: OpsLeafConfig = {
  entity: "execution",
  title: "Execution history",
  desc: "The immutable log of every automation run — what ran, what triggered it, how long it took and whether it succeeded.",
  icon: History,
  idPrefix: "EXE",
  count: 24,
  initialSortKey: "ran",
  fields: [
    {
      key: "name",
      header: "Execution",
      kind: "primary",
      pool: [
        "Auto-tag",
        "Idle cleanup",
        "Compliance scan",
        "Quota raise",
        "Drift remediate",
        "Snapshot rotate",
        "Cost response",
      ],
      searchable: true,
    },
    {
      key: "source",
      header: "Source",
      kind: "text",
      pool: ["Policy", "Scheduled Task", "Bulk Operation", "Manual"],
      filter: true,
    },
    {
      key: "trigger",
      header: "Trigger",
      kind: "text",
      pool: TRIGGERS,
      filter: true,
    },
    {
      key: "duration",
      header: "Duration",
      kind: "rel",
      pool: ["<1s", "8s", "45s", "3 min", "14 min"],
    },
    {
      key: "result",
      header: "Result",
      kind: "status",
      pool: RUN_STATUS,
      filter: true,
    },
    { key: "ran", header: "Ran", kind: "date" },
  ],
  stats: [
    { label: "Executions", kind: "count" },
    {
      label: "Succeeded",
      kind: "where",
      field: "result",
      eq: ["Succeeded"],
      tone: "ok",
    },
    {
      label: "Failed",
      kind: "where",
      field: "result",
      eq: ["Failed"],
      tone: "danger",
    },
    {
      label: "Running",
      kind: "where",
      field: "result",
      eq: ["Running"],
      tone: "warn",
    },
  ],
  toolbar: [
    { label: "Refresh", icon: <RefreshCcw size={15} />, primary: true },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "View Logs", "Re-run", "Export"],
};

const INTEGRATIONS: OpsLeafConfig = {
  entity: "integration",
  title: "Notification integrations",
  desc: "The channels automation and alerts emit through — email, chat, incident and webhook targets, and their delivery health.",
  icon: Plug,
  idPrefix: "NI",
  count: 12,
  fields: [
    {
      key: "name",
      header: "Integration",
      kind: "primary",
      pool: [
        "Ops Email",
        "Platform Slack",
        "Security Teams",
        "PagerDuty",
        "ServiceNow",
        "Generic Webhook",
        "SIEM Forwarder",
      ],
      searchable: true,
    },
    {
      key: "channel",
      header: "Channel",
      kind: "text",
      pool: ["Email", "Slack", "Teams", "PagerDuty", "Webhook"],
      filter: true,
    },
    {
      key: "events",
      header: "Subscribed Events",
      kind: "num",
      min: 1,
      max: 40,
    },
    {
      key: "delivered",
      header: "Delivered (30d)",
      kind: "num",
      min: 0,
      max: 5000,
    },
    {
      key: "health",
      header: "Health",
      kind: "status",
      pool: ["Healthy", "Healthy", "Degraded"],
      filter: true,
    },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Enabled", "Enabled", "Paused"],
      filter: true,
    },
  ],
  stats: [
    { label: "Integrations", kind: "count" },
    {
      label: "Enabled",
      kind: "where",
      field: "status",
      eq: ["Enabled"],
      tone: "ok",
    },
    {
      label: "Degraded",
      kind: "where",
      field: "health",
      eq: ["Degraded"],
      tone: "warn",
    },
    { label: "Delivered (30d)", kind: "sum", field: "delivered" },
  ],
  toolbar: [
    { label: "New Integration", icon: <Plus size={15} />, primary: true },
    { label: "Test", icon: <Play size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Test", "Pause", "Delete"],
};

export const AUTOMATION_LEAVES: Leaf[] = [
  {
    id: "automation-policies",
    label: "Automation Policies",
    Icon: Cog,
    render: () => <OpsLeaf cfg={POLICIES} />,
  },
  {
    id: "automation-templates",
    label: "Templates",
    Icon: FileCode2,
    render: () => <OpsLeaf cfg={TEMPLATES} />,
  },
  {
    id: "scheduled-tasks",
    label: "Scheduled Tasks",
    Icon: CalendarClock,
    render: () => <OpsLeaf cfg={SCHEDULED} />,
  },
  {
    id: "provisioning-jobs",
    label: "Provisioning Jobs",
    Icon: Rocket,
    render: () => <OpsLeaf cfg={JOBS} />,
  },
  {
    id: "bulk-operations",
    label: "Bulk Operations",
    Icon: Layers,
    render: () => <OpsLeaf cfg={BULK} />,
  },
  {
    id: "execution-history",
    label: "Execution History",
    Icon: History,
    render: () => <OpsLeaf cfg={EXECUTION} />,
  },
  {
    id: "notification-integrations",
    label: "Notification Integrations",
    Icon: Plug,
    render: () => <OpsLeaf cfg={INTEGRATIONS} />,
  },
];
