/* eslint-disable i18next/no-literal-string -- CloudGuard Workspace Operations → Catalog & Discovery */
import React from "react";
import {
  Compass,
  Search as SearchIcon,
  Tags,
  ShieldCheck,
  Bookmark,
  Star,
  Plus,
  RefreshCcw,
  Download,
  Upload,
  Boxes,
  Filter,
} from "lucide-react";
import {
  OpsLeaf,
  WORKSPACES,
  BUSINESS_UNITS,
  OWNERS,
  ENVIRONMENTS,
  type Leaf,
  type OpsLeafConfig,
} from "#/components/admin/pages/workspace-operations/ops-leaf";

/**
 * Catalog & Discovery — the enterprise "find and understand any workspace" layer:
 * the searchable catalog of every workspace, the cross-workspace search index,
 * the classification + tag taxonomy that makes discovery meaningful, and the
 * saved views / favourites that make it fast. Authoritative spec:
 * docs/workspace/workspace_module/…/Workspace Operations/Catalog & Discovery/.
 * Every leaf is generated from the shared ops-leaf framework engine.
 */

const CATALOG: OpsLeafConfig = {
  entity: "workspace",
  title: "Workspace catalog",
  desc: "The authoritative searchable catalog of every workspace in the organization — metadata, ownership, environment, classification and posture in one place.",
  icon: Compass,
  primaryIcon: Boxes,
  idPrefix: "WS",
  count: 20,
  initialSortKey: "resources",
  fields: [
    {
      key: "name",
      header: "Workspace",
      kind: "primary",
      pool: WORKSPACES,
      searchable: true,
    },
    {
      key: "businessUnit",
      header: "Business Unit",
      kind: "text",
      pool: BUSINESS_UNITS,
      filter: true,
      searchable: true,
    },
    {
      key: "environment",
      header: "Environment",
      kind: "text",
      pool: ENVIRONMENTS,
      filter: true,
    },
    {
      key: "classification",
      header: "Classification",
      kind: "sev",
      pool: ["Public", "Internal", "Confidential", "Restricted"],
      filter: true,
    },
    {
      key: "owner",
      header: "Owner",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    { key: "resources", header: "Resources", kind: "num", min: 20, max: 2000 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Active", "Archived", "Paused"],
    },
    { key: "updated", header: "Updated", kind: "date" },
  ],
  stats: [
    { label: "Workspaces", kind: "count" },
    {
      label: "Active",
      kind: "where",
      field: "status",
      eq: ["Active"],
      tone: "ok",
    },
    {
      label: "Production",
      kind: "where",
      field: "environment",
      eq: ["Production"],
    },
    {
      label: "Restricted",
      kind: "where",
      field: "classification",
      eq: ["Restricted"],
      tone: "warn",
    },
    {
      label: "Archived",
      kind: "where",
      field: "status",
      eq: ["Archived"],
      tone: "neutral",
    },
    { label: "Total Resources", kind: "sum", field: "resources" },
  ],
  toolbar: [
    { label: "New Workspace", icon: <Plus size={15} />, primary: true },
    { label: "Refresh Catalog", icon: <RefreshCcw size={15} /> },
    { label: "Import", icon: <Upload size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Open", "Edit Metadata", "Classify", "Export"],
  bulk: [
    { label: "Classify", icon: <ShieldCheck size={13} /> },
    { label: "Export", icon: <Download size={13} /> },
  ],
};

const SEARCH: OpsLeafConfig = {
  entity: "indexed source",
  title: "Enterprise search index",
  desc: "The cross-workspace search index — the sources indexed for organization-wide discovery, their freshness and coverage.",
  icon: SearchIcon,
  idPrefix: "IDX",
  count: 14,
  initialSortKey: "items",
  fields: [
    {
      key: "source",
      header: "Indexed Source",
      kind: "primary",
      pool: [
        "Workspaces",
        "Resources",
        "Policies",
        "Tags",
        "Owners",
        "Approvals",
        "Automation",
        "Audit Events",
        "Classifications",
        "Cloud Accounts",
        "Clusters",
        "Cost Records",
      ],
      searchable: true,
    },
    {
      key: "category",
      header: "Category",
      kind: "text",
      pool: ["Inventory", "Governance", "Operations", "Security"],
      filter: true,
    },
    { key: "items", header: "Indexed Items", kind: "num", min: 40, max: 12000 },
    { key: "coverage", header: "Coverage", kind: "pct", min: 82, max: 100 },
    {
      key: "lastIndexed",
      header: "Last Indexed",
      kind: "rel",
      pool: ["2 min", "18 min", "1 h", "6 h"],
    },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Healthy", "Healthy", "Healthy", "Degraded"],
      filter: true,
    },
  ],
  stats: [
    { label: "Indexed Sources", kind: "count" },
    {
      label: "Healthy",
      kind: "where",
      field: "status",
      eq: ["Healthy"],
      tone: "ok",
    },
    {
      label: "Degraded",
      kind: "where",
      field: "status",
      eq: ["Degraded"],
      tone: "warn",
    },
    { label: "Indexed Items", kind: "sum", field: "items" },
    {
      label: "Avg Coverage",
      kind: "avg",
      field: "coverage",
      suffix: "%",
      tone: (v) => (v >= 90 ? "ok" : "warn"),
    },
  ],
  toolbar: [
    { label: "Configure Index", icon: <Filter size={15} />, primary: true },
    { label: "Reindex", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Reindex", "Configure"],
};

const CLASSIFICATIONS: OpsLeafConfig = {
  entity: "classification",
  title: "Classifications",
  desc: "The data-classification taxonomy applied across workspaces — sensitivity levels, the policies they attach and their coverage.",
  icon: ShieldCheck,
  idPrefix: "CLS",
  count: 12,
  fields: [
    {
      key: "label",
      header: "Classification",
      kind: "primary",
      pool: [
        "Public",
        "Internal",
        "Confidential",
        "Restricted",
        "PII",
        "PCI",
        "PHI",
        "Trade Secret",
        "Regulated",
        "Export-Controlled",
      ],
      searchable: true,
    },
    {
      key: "sensitivity",
      header: "Sensitivity",
      kind: "sev",
      pool: ["Low", "Medium", "High", "Critical"],
      filter: true,
    },
    { key: "workspaces", header: "Workspaces", kind: "num", min: 1, max: 60 },
    {
      key: "policy",
      header: "Attached Policy",
      kind: "text",
      pool: [
        "Encryption",
        "Access Review",
        "Retention",
        "Egress Control",
        "Masking",
      ],
      filter: true,
    },
    { key: "owner", header: "Owner", kind: "text", pool: OWNERS, filter: true },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Draft"],
    },
  ],
  stats: [
    { label: "Classifications", kind: "count" },
    {
      label: "Critical",
      kind: "where",
      field: "sensitivity",
      eq: ["Critical"],
      tone: "danger",
    },
    {
      label: "High",
      kind: "where",
      field: "sensitivity",
      eq: ["High"],
      tone: "warn",
    },
    {
      label: "Active",
      kind: "where",
      field: "status",
      eq: ["Active"],
      tone: "ok",
    },
    { label: "Classified Workspaces", kind: "sum", field: "workspaces" },
  ],
  toolbar: [
    { label: "New Classification", icon: <Plus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Attach Policy", "Delete"],
};

const TAGS: OpsLeafConfig = {
  entity: "tag",
  title: "Tags",
  desc: "The governance tag taxonomy — the keys and values used to organize, cost-allocate and discover workspaces, and their adoption.",
  icon: Tags,
  idPrefix: "TAG",
  count: 16,
  initialSortKey: "usage",
  fields: [
    {
      key: "tag",
      header: "Tag Key",
      kind: "primary",
      pool: [
        "cost-center",
        "owner",
        "environment",
        "data-class",
        "team",
        "project",
        "compliance",
        "lifecycle",
        "region",
        "criticality",
      ],
      searchable: true,
    },
    {
      key: "category",
      header: "Category",
      kind: "text",
      pool: ["Cost", "Ownership", "Governance", "Operations"],
      filter: true,
    },
    { key: "usage", header: "Usage", kind: "num", min: 2, max: 400 },
    {
      key: "required",
      header: "Required",
      kind: "status",
      pool: ["Enabled", "Draft"],
      filter: true,
    },
    { key: "owner", header: "Owner", kind: "text", pool: OWNERS, filter: true },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Deprecated"],
    },
  ],
  stats: [
    { label: "Tag Keys", kind: "count" },
    {
      label: "Required",
      kind: "where",
      field: "required",
      eq: ["Enabled"],
      tone: "ok",
    },
    {
      label: "Deprecated",
      kind: "where",
      field: "status",
      eq: ["Deprecated"],
      tone: "warn",
    },
    { label: "Total Usage", kind: "sum", field: "usage" },
  ],
  toolbar: [
    { label: "New Tag", icon: <Plus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Set Required", "Deprecate"],
};

const SAVED_VIEWS: OpsLeafConfig = {
  entity: "saved view",
  title: "Saved views",
  desc: "Reusable catalog views — the saved filter/column sets teams use to slice the workspace estate, and how widely they are shared.",
  icon: Bookmark,
  idPrefix: "SV",
  count: 14,
  initialSortKey: "uses",
  fields: [
    {
      key: "name",
      header: "View",
      kind: "primary",
      pool: [
        "Production Workspaces",
        "Orphaned Resources",
        "PCI Scope",
        "My Team",
        "Idle Sandboxes",
        "High Cost",
        "Pending Reviews",
        "Non-Compliant",
        "New This Quarter",
        "Restricted Data",
      ],
      searchable: true,
    },
    {
      key: "scope",
      header: "Scope",
      kind: "text",
      pool: ["Workspaces", "Resources", "Requests", "Alerts"],
      filter: true,
    },
    {
      key: "visibility",
      header: "Visibility",
      kind: "text",
      pool: ["Private", "Team", "Organization"],
      filter: true,
    },
    {
      key: "owner",
      header: "Owner",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    { key: "uses", header: "Uses", kind: "num", min: 1, max: 300 },
    { key: "updated", header: "Updated", kind: "date" },
  ],
  stats: [
    { label: "Saved Views", kind: "count" },
    {
      label: "Shared (Org)",
      kind: "where",
      field: "visibility",
      eq: ["Organization"],
      tone: "ok",
    },
    { label: "Team", kind: "where", field: "visibility", eq: ["Team"] },
    {
      label: "Private",
      kind: "where",
      field: "visibility",
      eq: ["Private"],
      tone: "neutral",
    },
    { label: "Total Uses", kind: "sum", field: "uses" },
  ],
  toolbar: [
    { label: "New View", icon: <Plus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["Open", "Edit", "Share", "Duplicate", "Delete"],
};

const FAVORITES: OpsLeafConfig = {
  entity: "favorite",
  title: "Favorites",
  desc: "Pinned workspaces and resources — quick access to the items an operator returns to most.",
  icon: Star,
  idPrefix: "FAV",
  count: 12,
  fields: [
    {
      key: "name",
      header: "Item",
      kind: "primary",
      pool: WORKSPACES,
      searchable: true,
    },
    {
      key: "type",
      header: "Type",
      kind: "text",
      pool: ["Workspace", "Resource", "Saved View", "Report"],
      filter: true,
    },
    {
      key: "workspace",
      header: "Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
      searchable: true,
    },
    {
      key: "owner",
      header: "Pinned By",
      kind: "text",
      pool: OWNERS,
      filter: true,
    },
    { key: "pinned", header: "Pinned", kind: "date" },
  ],
  stats: [
    { label: "Favorites", kind: "count" },
    { label: "Workspaces", kind: "where", field: "type", eq: ["Workspace"] },
    { label: "Resources", kind: "where", field: "type", eq: ["Resource"] },
    { label: "Saved Views", kind: "where", field: "type", eq: ["Saved View"] },
  ],
  toolbar: [
    { label: "Pin Item", icon: <Plus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
  ],
  rowMenu: ["Open", "Unpin"],
};

export const CATALOG_LEAVES: Leaf[] = [
  {
    id: "workspace-catalog",
    label: "Workspace Catalog",
    Icon: Compass,
    render: () => <OpsLeaf cfg={CATALOG} />,
  },
  {
    id: "enterprise-search",
    label: "Enterprise Search",
    Icon: SearchIcon,
    render: () => <OpsLeaf cfg={SEARCH} />,
  },
  {
    id: "classifications",
    label: "Classifications",
    Icon: ShieldCheck,
    render: () => <OpsLeaf cfg={CLASSIFICATIONS} />,
  },
  {
    id: "tags",
    label: "Tags",
    Icon: Tags,
    render: () => <OpsLeaf cfg={TAGS} />,
  },
  {
    id: "saved-views",
    label: "Saved Views",
    Icon: Bookmark,
    render: () => <OpsLeaf cfg={SAVED_VIEWS} />,
  },
  {
    id: "favorites",
    label: "Favorites",
    Icon: Star,
    render: () => <OpsLeaf cfg={FAVORITES} />,
  },
];
