/* eslint-disable i18next/no-literal-string -- CloudGuard Workspace Operations → Requests & Approvals */
import React from "react";
import {
  Inbox,
  Stamp,
  FilePlus2,
  Boxes,
  Share2,
  UserCheck,
  History,
  Check,
  X,
  RefreshCcw,
  Download,
  ArrowUpRight,
  UserPlus,
} from "lucide-react";
import {
  OpsLeaf,
  WORKSPACES,
  BUSINESS_UNITS,
  OWNERS,
  type Leaf,
  type OpsLeafConfig,
} from "#/components/admin/pages/workspace-operations/ops-leaf";

/**
 * Requests & Approvals — the request-to-decision worklist for the whole estate:
 * everything waiting on a human (or delegated) decision — new workspace requests,
 * resource requests, cross-workspace access, the approval queue, delegated
 * approvals, and the immutable request history. Authoritative spec:
 * docs/workspace/workspace_module/…/Workspace Operations/Requests & Approvals/.
 */

const TYPES = [
  "Workspace",
  "Resource",
  "Access",
  "Quota Increase",
  "Policy Exception",
];
const PRIORITIES = ["Low", "Medium", "High", "Critical"];
const SLA = ["Within SLA", "Within SLA", "Approaching", "Breached"];
const REQ_STATUS = ["Pending", "In Review", "Approved", "Rejected"];

const PENDING: OpsLeafConfig = {
  entity: "request",
  title: "Pending requests",
  desc: "Every request currently awaiting a decision across the organization — the operator's single worklist, SLA-first.",
  icon: Inbox,
  idPrefix: "REQ",
  count: 20,
  initialSortKey: "age",
  fields: [
    {
      key: "summary",
      header: "Request",
      kind: "primary",
      pool: [
        "New workspace",
        "Add S3 bucket",
        "Grant read access",
        "Increase CPU quota",
        "Policy exception",
        "Cross-workspace link",
        "New database",
        "Elevate role",
      ],
      searchable: true,
    },
    { key: "type", header: "Type", kind: "text", pool: TYPES, filter: true },
    {
      key: "workspace",
      header: "Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
      searchable: true,
    },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    {
      key: "priority",
      header: "Priority",
      kind: "sev",
      pool: PRIORITIES,
      filter: true,
    },
    { key: "slaState", header: "SLA", kind: "status", pool: SLA, filter: true },
    { key: "age", header: "Age", kind: "num", min: 1, max: 72 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Pending", "Pending", "In Review"],
    },
  ],
  stats: [
    { label: "Pending", kind: "count", tone: "warn" },
    {
      label: "Critical",
      kind: "where",
      field: "priority",
      eq: ["Critical"],
      tone: "danger",
    },
    {
      label: "SLA Breached",
      kind: "where",
      field: "slaState",
      eq: ["Breached"],
      tone: "danger",
    },
    {
      label: "Approaching SLA",
      kind: "where",
      field: "slaState",
      eq: ["Approaching"],
      tone: "warn",
    },
    { label: "In Review", kind: "where", field: "status", eq: ["In Review"] },
  ],
  toolbar: [
    { label: "Approve", icon: <Check size={15} />, primary: true },
    { label: "Reject", icon: <X size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["Review", "Approve", "Reject", "Reassign", "Export"],
  bulk: [
    { label: "Approve", icon: <Check size={13} /> },
    { label: "Reject", icon: <X size={13} /> },
  ],
};

const QUEUE: OpsLeafConfig = {
  entity: "approval",
  title: "Approval queue",
  desc: "The approvals assigned to you or your groups — decide, escalate or delegate. SLA-first ordering keeps breaches at the top.",
  icon: Stamp,
  idPrefix: "APR",
  count: 18,
  initialSortKey: "age",
  fields: [
    {
      key: "summary",
      header: "Approval",
      kind: "primary",
      pool: [
        "Approve workspace",
        "Approve access",
        "Approve quota",
        "Approve exception",
        "Approve resource",
      ],
      searchable: true,
    },
    { key: "type", header: "Type", kind: "text", pool: TYPES, filter: true },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    {
      key: "approver",
      header: "Assigned To",
      kind: "text",
      pool: [...OWNERS, "Governance Board"],
      filter: true,
    },
    {
      key: "priority",
      header: "Priority",
      kind: "sev",
      pool: PRIORITIES,
      filter: true,
    },
    { key: "slaState", header: "SLA", kind: "status", pool: SLA, filter: true },
    { key: "age", header: "Age (h)", kind: "num", min: 1, max: 48 },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Pending", "In Review", "Escalated"],
    },
  ],
  stats: [
    { label: "In Queue", kind: "count", tone: "warn" },
    {
      label: "SLA Breached",
      kind: "where",
      field: "slaState",
      eq: ["Breached"],
      tone: "danger",
    },
    {
      label: "Escalated",
      kind: "where",
      field: "status",
      eq: ["Escalated"],
      tone: "warn",
    },
    {
      label: "Critical",
      kind: "where",
      field: "priority",
      eq: ["Critical"],
      tone: "danger",
    },
  ],
  toolbar: [
    { label: "Approve", icon: <Check size={15} />, primary: true },
    { label: "Reject", icon: <X size={15} /> },
    { label: "Escalate", icon: <ArrowUpRight size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
  ],
  rowMenu: ["Review", "Approve", "Reject", "Escalate", "Delegate"],
  bulk: [
    { label: "Approve", icon: <Check size={13} /> },
    { label: "Reject", icon: <X size={13} /> },
  ],
};

const CREATION: OpsLeafConfig = {
  entity: "creation request",
  title: "Workspace creation requests",
  desc: "Requests to stand up a new workspace — with the requested environment, business unit and the provisioning that follows approval.",
  icon: FilePlus2,
  idPrefix: "WCR",
  count: 16,
  initialSortKey: "submitted",
  fields: [
    {
      key: "name",
      header: "Requested Workspace",
      kind: "primary",
      pool: [
        "Payments EU",
        "Retail Mobile",
        "ML Research",
        "Fraud Analytics",
        "Partner Portal",
        "Data Warehouse",
        "IoT Ingest",
        "Test Bench",
      ],
      searchable: true,
    },
    {
      key: "environment",
      header: "Environment",
      kind: "text",
      pool: ["Production", "Staging", "Development", "Sandbox"],
      filter: true,
    },
    {
      key: "businessUnit",
      header: "Business Unit",
      kind: "text",
      pool: BUSINESS_UNITS,
      filter: true,
    },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    { key: "submitted", header: "Submitted", kind: "date" },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Pending", "In Review", "Approved", "Rejected"],
      filter: true,
    },
  ],
  stats: [
    { label: "Requests", kind: "count" },
    {
      label: "Pending",
      kind: "where",
      field: "status",
      eq: ["Pending", "In Review"],
      tone: "warn",
    },
    {
      label: "Approved",
      kind: "where",
      field: "status",
      eq: ["Approved"],
      tone: "ok",
    },
    {
      label: "Rejected",
      kind: "where",
      field: "status",
      eq: ["Rejected"],
      tone: "neutral",
    },
    {
      label: "Production",
      kind: "where",
      field: "environment",
      eq: ["Production"],
    },
  ],
  toolbar: [
    { label: "New Request", icon: <FilePlus2 size={15} />, primary: true },
    { label: "Approve", icon: <Check size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["Review", "Approve", "Reject", "Provision", "Export"],
};

const RESOURCE: OpsLeafConfig = {
  entity: "resource request",
  title: "Resource requests",
  desc: "Requests for resources inside an existing workspace — compute, storage, databases, network — against quota and policy.",
  icon: Boxes,
  idPrefix: "RSR",
  count: 18,
  initialSortKey: "submitted",
  fields: [
    {
      key: "resource",
      header: "Resource",
      kind: "primary",
      pool: [
        "EC2 fleet",
        "S3 bucket",
        "RDS instance",
        "EKS namespace",
        "Load balancer",
        "KMS key",
        "VPC peering",
        "Elastic IP",
      ],
      searchable: true,
    },
    {
      key: "workspace",
      header: "Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
      searchable: true,
    },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
    },
    {
      key: "quotaImpact",
      header: "Quota Impact",
      kind: "sev",
      pool: ["Low", "Medium", "High"],
      filter: true,
    },
    { key: "submitted", header: "Submitted", kind: "date" },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: REQ_STATUS,
      filter: true,
    },
  ],
  stats: [
    { label: "Requests", kind: "count" },
    {
      label: "Pending",
      kind: "where",
      field: "status",
      eq: ["Pending", "In Review"],
      tone: "warn",
    },
    {
      label: "Approved",
      kind: "where",
      field: "status",
      eq: ["Approved"],
      tone: "ok",
    },
    {
      label: "High Quota Impact",
      kind: "where",
      field: "quotaImpact",
      eq: ["High"],
      tone: "warn",
    },
  ],
  toolbar: [
    { label: "New Request", icon: <FilePlus2 size={15} />, primary: true },
    { label: "Approve", icon: <Check size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["Review", "Approve", "Reject", "Check Quota"],
};

const CROSS: OpsLeafConfig = {
  entity: "cross-workspace request",
  title: "Cross-workspace requests",
  desc: "Requests to connect or share across workspace boundaries — the highest-scrutiny path, reviewed against isolation and trust policy.",
  icon: Share2,
  idPrefix: "XWR",
  count: 14,
  initialSortKey: "submitted",
  fields: [
    {
      key: "summary",
      header: "Request",
      kind: "primary",
      pool: [
        "Share dataset",
        "Peer VPC",
        "Grant cross access",
        "Publish shared asset",
        "Federate identity",
      ],
      searchable: true,
    },
    {
      key: "source",
      header: "Source Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
      searchable: true,
    },
    {
      key: "target",
      header: "Target Workspace",
      kind: "text",
      pool: WORKSPACES,
      filter: true,
    },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
    },
    {
      key: "risk",
      header: "Risk",
      kind: "sev",
      pool: ["Low", "Medium", "High", "Critical"],
      filter: true,
    },
    { key: "submitted", header: "Submitted", kind: "date" },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: REQ_STATUS,
      filter: true,
    },
  ],
  stats: [
    { label: "Requests", kind: "count" },
    {
      label: "Pending",
      kind: "where",
      field: "status",
      eq: ["Pending", "In Review"],
      tone: "warn",
    },
    {
      label: "High/Critical Risk",
      kind: "where",
      field: "risk",
      eq: ["High", "Critical"],
      tone: "danger",
    },
    {
      label: "Approved",
      kind: "where",
      field: "status",
      eq: ["Approved"],
      tone: "ok",
    },
  ],
  toolbar: [
    { label: "New Request", icon: <FilePlus2 size={15} />, primary: true },
    { label: "Approve", icon: <Check size={15} /> },
    { label: "Reject", icon: <X size={15} /> },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
  ],
  rowMenu: ["Review", "Approve", "Reject", "Assess Risk"],
};

const DELEGATED: OpsLeafConfig = {
  entity: "delegation",
  title: "Delegated approvals",
  desc: "Approval authority delegated to another approver for a window — who can approve what, on whose behalf, and until when.",
  icon: UserCheck,
  idPrefix: "DLG",
  count: 12,
  fields: [
    {
      key: "delegate",
      header: "Delegate",
      kind: "primary",
      pool: OWNERS,
      searchable: true,
    },
    {
      key: "delegator",
      header: "On Behalf Of",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    { key: "scope", header: "Scope", kind: "text", pool: TYPES, filter: true },
    { key: "expires", header: "Expires", kind: "date" },
    {
      key: "status",
      header: "Status",
      kind: "status",
      pool: ["Active", "Active", "Expired"],
      filter: true,
    },
  ],
  stats: [
    { label: "Delegations", kind: "count" },
    {
      label: "Active",
      kind: "where",
      field: "status",
      eq: ["Active"],
      tone: "ok",
    },
    {
      label: "Expired",
      kind: "where",
      field: "status",
      eq: ["Expired"],
      tone: "neutral",
    },
  ],
  toolbar: [
    { label: "New Delegation", icon: <UserPlus size={15} />, primary: true },
    { label: "Refresh", icon: <RefreshCcw size={15} /> },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Edit", "Revoke"],
};

const HISTORY: OpsLeafConfig = {
  entity: "decision",
  title: "Request history",
  desc: "The immutable record of every decided request — who requested, who decided, the outcome and the time-to-decision.",
  icon: History,
  idPrefix: "RH",
  count: 22,
  initialSortKey: "decided",
  fields: [
    {
      key: "summary",
      header: "Request",
      kind: "primary",
      pool: [
        "New workspace",
        "Add resource",
        "Grant access",
        "Quota increase",
        "Policy exception",
        "Cross-workspace link",
      ],
      searchable: true,
    },
    { key: "type", header: "Type", kind: "text", pool: TYPES, filter: true },
    {
      key: "requester",
      header: "Requester",
      kind: "text",
      pool: OWNERS,
      filter: true,
      searchable: true,
    },
    {
      key: "decidedBy",
      header: "Decided By",
      kind: "text",
      pool: OWNERS,
      filter: true,
    },
    {
      key: "outcome",
      header: "Outcome",
      kind: "status",
      pool: ["Approved", "Approved", "Rejected", "Withdrawn"],
      filter: true,
    },
    {
      key: "ttd",
      header: "Time to Decision (h)",
      kind: "num",
      min: 1,
      max: 96,
    },
    { key: "decided", header: "Decided", kind: "date" },
  ],
  stats: [
    { label: "Decisions", kind: "count" },
    {
      label: "Approved",
      kind: "where",
      field: "outcome",
      eq: ["Approved"],
      tone: "ok",
    },
    {
      label: "Rejected",
      kind: "where",
      field: "outcome",
      eq: ["Rejected"],
      tone: "warn",
    },
    { label: "Avg Time to Decision", kind: "avg", field: "ttd", suffix: "h" },
  ],
  toolbar: [
    { label: "Refresh", icon: <RefreshCcw size={15} />, primary: true },
    { label: "Export", icon: <Download size={15} /> },
  ],
  rowMenu: ["View", "Export"],
};

export const REQUESTS_LEAVES: Leaf[] = [
  {
    id: "pending-requests",
    label: "Pending Requests",
    Icon: Inbox,
    render: () => <OpsLeaf cfg={PENDING} />,
  },
  {
    id: "approval-queue",
    label: "Approval Queue",
    Icon: Stamp,
    render: () => <OpsLeaf cfg={QUEUE} />,
  },
  {
    id: "workspace-creation-requests",
    label: "Workspace Creation",
    Icon: FilePlus2,
    render: () => <OpsLeaf cfg={CREATION} />,
  },
  {
    id: "resource-requests",
    label: "Resource Requests",
    Icon: Boxes,
    render: () => <OpsLeaf cfg={RESOURCE} />,
  },
  {
    id: "cross-workspace-requests",
    label: "Cross-Workspace",
    Icon: Share2,
    render: () => <OpsLeaf cfg={CROSS} />,
  },
  {
    id: "delegated-approvals",
    label: "Delegated Approvals",
    Icon: UserCheck,
    render: () => <OpsLeaf cfg={DELEGATED} />,
  },
  {
    id: "request-history",
    label: "Request History",
    Icon: History,
    render: () => <OpsLeaf cfg={HISTORY} />,
  },
];
