import {
  type RouteConfig,
  layout,
  index,
  route,
} from "@react-router/dev/routes";

export default [
  layout("routes/root-layout.tsx", [
    index("routes/home.tsx"),
    route("accept-tos", "routes/accept-tos.tsx"),
    route("agent-control-plane", "routes/acp.tsx", [
      index("routes/acp-overview.tsx", { id: "acp-overview-index" }),
      route("overview", "routes/acp-overview.tsx"),
      route("runs", "routes/acp-runs.tsx"),
      route("sandboxes", "routes/acp-sandboxes.tsx"),
      route("monitoring", "routes/acp-monitoring.tsx"),
      route("enforcement", "routes/acp-enforcement.tsx"),
      route("audit", "routes/acp-audit.tsx"),
      route("incidents", "routes/acp-incidents.tsx"),
    ]),
    route("settings", "routes/settings.tsx", [
      index("routes/settings-profile.tsx", { id: "settings-profile-index" }),
      route("profile", "routes/settings-profile.tsx"),
      route("theme", "routes/settings-theme.tsx"),
      route("security", "routes/settings-security.tsx"),
      route("workspace", "routes/settings-workspace.tsx"),
      route("sandbox-compute", "routes/settings-sandbox-compute.tsx"),
      route("audit-log", "routes/settings-audit-log.tsx"),
      route("org", "routes/org-settings.tsx"),
      route("members", "routes/settings-members.tsx"),
      route("user-roles", "routes/settings-user-roles.tsx"),
      route("plan", "routes/settings-plan.tsx"),
      route("billing", "routes/settings-billing-sub.tsx"),
      route("notifications", "routes/settings-notifications.tsx"),
      route("support", "routes/settings-support.tsx"),
      route("environments", "routes/settings-environments.tsx"),
      route("network", "routes/settings-network.tsx"),
      route("compliance", "routes/settings-compliance.tsx"),
      route("usage", "routes/settings-usage.tsx"),
      route("limits", "routes/settings-limits.tsx"),
      route("service-accounts", "routes/settings-service-accounts.tsx"),
      route("agent-guardrails", "routes/settings-agent-guardrails.tsx"),
      route("isolation", "routes/settings-isolation.tsx"),
      route("encryption", "routes/settings-encryption.tsx"),
      route("data-residency", "routes/settings-data-residency.tsx"),
      route("webhooks", "routes/settings-webhooks.tsx"),
      route("connectors", "routes/settings-connectors.tsx"),
      route("vault", "routes/settings-vault.tsx"),
      route("mcp", "routes/mcp-settings.tsx"),
      route("user", "routes/user-settings.tsx"),
      route("integrations", "routes/settings-integrations.tsx"),
      route("git-providers", "routes/git-settings.tsx"),
      route("app", "routes/app-settings.tsx"),
      route("billing", "routes/billing.tsx"),
      route("secrets", "routes/secrets-settings.tsx"),
      route("api-keys", "routes/api-keys.tsx"),
    ]),
    route("conversations/:conversationId", "routes/conversation.tsx"),
    route("microagent-management", "routes/microagent-management.tsx"),
  ]),
] satisfies RouteConfig;
