#!/usr/bin/env python3
"""
Generate a Markdown index of every SKILL.md in the skills tree.

Produces ``cloudguard-runtime/skills/INDEX.md`` with:
- Section per provider (aws, azure, gcp, shared, internal)
- Sub-section per category (identity, posture, network, ...) and per service
  (s3, ec2, iam, ...) where declared
- One row per skill with name, description, file link
- Stats footer (totals by provider/category/service)

Designed for scale: at 98+ skills, a hand-maintained INDEX.md drifts within
weeks. Run this script after every skill add/remove and commit the result.

Usage:
    python scripts/generate_skill_index.py
    python scripts/generate_skill_index.py --root /workspace/cloudguard-runtime/skills
    python scripts/generate_skill_index.py --output INDEX.md
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from openhands.services.skills.registry import SkillRegistry, SkillEntry  # noqa: E402


_PROVIDER_HEADERS = {
    "aws":      "## AWS",
    "azure":    "## Azure",
    "gcp":      "## GCP",
    "shared":   "## Shared (cross-cloud)",
    "internal": "## Internal (not user-facing)",
}


def _section_for_skill(s: SkillEntry) -> str:
    """Group key for sub-sectioning. Service if declared, else category."""
    return s.service or s.category


def render_index(registry: SkillRegistry, root: Path) -> str:
    stats = registry.stats()
    all_skills = registry.all()

    # Group: provider → section_key → [skills]
    grouped: dict[str, dict[str, list[SkillEntry]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for s in all_skills:
        grouped[s.provider][_section_for_skill(s)].append(s)

    lines: list[str] = []
    lines.append("# CloudGuard Skill Index")
    lines.append("")
    lines.append(
        "> **Auto-generated by `scripts/generate_skill_index.py` — do not edit by hand.**  "
        "Re-run after every skill add/remove and commit the diff."
    )
    lines.append("")
    lines.append(f"**Total skills**: {stats['total']}  ")
    if stats.get("by_provider"):
        items = ", ".join(
            f"{p}={n}" for p, n in sorted(stats["by_provider"].items())
        )
        lines.append(f"**By provider**: {items}  ")
    if stats.get("by_service"):
        n_services = len(stats["by_service"])
        lines.append(f"**Services declared**: {n_services}")
    lines.append("")

    # Render per provider in priority order
    provider_order = ["aws", "azure", "gcp", "shared", "internal"]
    for provider in provider_order:
        if provider not in grouped:
            continue
        lines.append(_PROVIDER_HEADERS[provider])
        lines.append("")
        section_keys = sorted(grouped[provider].keys())
        for section in section_keys:
            skills = sorted(grouped[provider][section], key=lambda s: s.name)
            lines.append(f"### {section}")
            lines.append("")
            lines.append("| Skill | Description | Source |")
            lines.append("|-------|-------------|--------|")
            for s in skills:
                src_path = Path(s.source_path)
                try:
                    rel = src_path.relative_to(root)
                except ValueError:
                    rel = Path(s.source_path).name
                desc = s.description.replace("|", "\\|") if s.description else "_(no description)_"
                lines.append(f"| `{s.name}` | {desc} | [{rel}]({rel}) |")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("## Stats")
    lines.append("")
    if stats.get("by_category"):
        lines.append("### By Category")
        lines.append("")
        for cat, n in sorted(stats["by_category"].items()):
            lines.append(f"- **{cat}**: {n}")
        lines.append("")
    if stats.get("by_service"):
        lines.append("### By Service (AWS sub-categorization)")
        lines.append("")
        for svc, n in sorted(stats["by_service"].items()):
            lines.append(f"- **{svc}**: {n}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--root", type=Path,
                        default=Path("cloudguard-runtime/skills"),
                        help="Skills tree root")
    parser.add_argument("--output", type=Path, default=None,
                        help="Output path (default: {root}/INDEX.md)")
    parser.add_argument("--stdout", action="store_true",
                        help="Print to stdout instead of writing a file")
    args = parser.parse_args(argv)

    if not args.root.is_dir():
        print(f"error: root not found: {args.root}", file=sys.stderr)
        return 2

    output_path = args.output or args.root / "INDEX.md"

    registry = SkillRegistry(base_dir=args.root)
    rendered = render_index(registry, args.root)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    output_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
